[context.production.environment]
  REACT_APP_ENABLE_HISTORY = "true"

[context."mainnet-staging".environment]
  REACT_APP_CHAIN_ID = "1"

[context."master".environment]
  REACT_APP_ENABLE_HISTORY = "true"

[context.deploy-preview.environment]
  REACT_APP_CHAIN_ID = "1"

