name: Bots CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.bots
          push: false
          # tags: bengotch/simplewhale:${{ github.sha }}
